# Generated by Django 5.1.1 on 2026-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
