# Generated by Django 5.1.1 on 2026-04-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_failed_attempts_users_last_failed_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.users'),
        ),
    ]
